---
title: "Semantic Priming K. R."
author: "Michael Espero"
date: "2/11/2018"
output:
  html_document: default
---

```{r, echo=FALSE, results=FALSE, message=FALSE, cache=FALSE, warning=FALSE}
knitr::opts_chunk$set(error = TRUE, cache = FALSE, comment = NA, tidy = TRUE)
```

## Introduction

This is a demonstration regarding semantic priming. For problems or concerns, please contact me <michael.espero@cgu.edu>.

## Setup & Data Import
```{r Setup & Data Import, comment=F, message=F, warning=F}
set.seed(789)

# This build only requires that you have the "easypackages" library pre-installed. If it throws and error, try installing "easypackages" with install.packages()
require(easypackages)
packages(
  "tidyverse", "broom", "skimr", "plotly", "apaTables", "GGally",
  "caret", "psych", "haven", "car"
)

exp_1_spss_data <- read_sav("eprime/exp_1_spss_data.sav")
# We can make a pointer called "dat" to data we stored on Github.
# Here, we remove the filter column vector (4) from the spss data and filter the
# observations so only correct responses will be in dat.
dat <- exp_1_spss_data[, -4] %>%
  filter(TargetAcc == 1)

# Let's make sure we have only the correct responses.
# dat %>%
#  filter(TargetAcc == 1) %>%
#  count()

# We want Target Accuracy and Trial Type to work as factors
dat$TargetAcc <- as.factor(dat$TargetAcc)
dat$TrialType <- as.factor((dat$TrialType))

# dat <- read_csv(dat) # Read in the data from the specified url.

class(dat) # Is it a data frame?

dim(dat) # How many dimensions does our data have in terms of rows and columns?

skim(dat) # Now let's call up descriptive statistics and histograms.

# Is the dependent variable normally distributed?
skew(dat$TargetRT)
kurtosi(dat$TargetRT)
```

## Show

What do you notice?:

```{r show, echo=FALSE, comment=F, message=F, warning=F}
glimpse(dat)
# We can use this nifty function to make a matrix illustrating bivariate relationships in the data.
ggpairs(dat)

# 3D plots may be helpful in further exploration of how the data hangs together.
dat_2 <- exp_1_spss_data[, -4]

p0 <- plot_ly(data = dat_2, z = ~TargetRT, x = ~TrialType, y = ~TargetAcc, opacity = 0.6) %>% add_markers(color = ~TargetAcc)
p0
```

## Analyses

How might we test the data?:

```{r Analyze, echo=FALSE, comment=F, message=F, warning=F}

# Assumption Check: is the variance equal?
leveneTest(dat$TargetRT, group = dat$TrialType, center = mean)

# Specify the linear model
react_mod <- lm(TargetRT ~ TrialType, dat)

# Let's get some ANOVA output

kable(sjstats::anova_stats(react_mod), booktabs = T)

# Let's have another look with robust standard errors

Anova(
  react_mod, Type = "II",
  white.adjust = TRUE
)

# One more ANOVA, this time using the Welche's correction for unequal variance.

oneway.test(
  TargetRT ~ TrialType,
  data = dat_2,
  var.equal = FALSE
)

# How do the means line up? by trial type?
TukeyHSD(aov(react_mod))

plot(TukeyHSD(aov(TargetRT ~ TrialType, exp_1_spss_data)))
```

